### ISSUE TITLE
cannot connect 

### ISSUE THREAD

**Issue by maerzhase** [cuzzo/node-stanford-postagger#2]
Hi i installed everything and have the xml-rpc server running through your docker image...
if i try to run the standart example i get the following error in node.js:

{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' } undefined

any ideas?

**Comment by yubozhao** [comment]
same issue here   :(

**Comment by yubozhao** [comment]
@maerzhase 
just figure out the issue.  The localhost is not correctly exposed with boot2docker(mac)  If you do boot2docker ip, it will gives you the VM address.  Use that instead of localhost

**Comment by cuzzo** [comment]
Hey @maerzhase @yubozhao,

Sorry about that. Yeah, unfortunately Mac isn't very user-friendly with Docker. As @yubozhao noted, you can't use localhost. Wasn't aware of that as I develop on Linux.

Thanks for pointing that out @yubozhao!
